### ISSUE TITLE
Add touchable support to dashboard

### ISSUE THREAD

**Issue by ChrisBrinton** [ChrisBrinton/SensorIoT_app#6]
Add a touchable item to each CircularProgress element of each GaugeRow. When touched, this navigates to the history screen and issues an action to query the most recently selected time range (defaulting to a day) for the node and sensor type that was touched.

Make sure that it is still easy/possible to scroll dashboard without automatically going to history screen

**Comment by keyvanazami** [comment]
resolved after recent pullrequest
